"""add gpt_response to receipt

Revision ID: b64145b9a78a
Revises: f09ab842193c
Create Date: 2025-05-11 07:12:02.293259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64145b9a78a'
down_revision: Union[str, None] = 'f09ab842193c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('gpt_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'gpt_response')
    # ### end Alembic commands ###
